version: '3'
services:
    # Nginx Service
    nginx:
        build: ./nginx
        depends_on:
            - api
            - client
        ports:
            - "3050:80"
    # Postgres database
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    # Redis database
    redis:
        image: 'redis:latest'
    # Express API
    api:
        build: ./server
        image: "sameertakalkar24/complex_api"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    # Worker Service
    worker:
        build: ./worker
        image: "sameertakalkar24/complex_worker"
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    # Frontend Service
    client:
        build: ./client            
        image: "sameertakalkar24/complex_client"